/*
  Guest invite codes

  code   = a unique memorable animal word (lowercase)
           e.g. otter, panda, hedgehog
  access = "full", "evening", or "out-of-town"
           (which view file they see after entering their code)
           out-of-town = full day + Stay section for travelling guests

  Codes are case-insensitive when guests type them in.
  To add a guest, copy a line, pick an unused animal, set access.
*/

export const GUESTS = [
    { name: 'Mike (Groom)', code: 'otter', access: 'full' },
    { name: 'Jess (Bride)', code: 'panda', access: 'full' },
    { name: 'Debs', code: 'coot', access: 'full' },
    { name: 'Andy', code: 'waxwing', access: 'full' },
    { name: 'Andrea', code: 'newt', access: 'full' },
    { name: 'Wendy', code: 'chameleon', access: 'full' },
    { name: 'Andy', code: 'buzzard', access: 'full' },
    { name: 'Tom', code: 'walrus', access: 'full' },
    { name: 'Abbie', code: 'rabbit', access: 'full' },
    { name: 'Jake', code: 'eagle', access: 'full' },
    { name: 'Pei', code: 'chiffchaff', access: 'full' },
    { name: 'Lauren', code: 'lemur', access: 'full' },
    { name: 'Lewis', code: 'manatee', access: 'full' },
    { name: 'Eve', code: 'beagle', access: 'full' },
    { name: 'Eves Josh', code: 'falcon', access: 'full' },
    { name: 'Niamh', code: 'puma', access: 'full' },
    { name: 'Chelsy', code: 'blackcap', access: 'full' },
    { name: 'Jonny', code: 'armadillo', access: 'full' },
    { name: 'Tori', code: 'hare', access: 'full' },
    { name: 'Kay', code: 'woodpecker', access: 'full' },
    { name: 'Katie Lou', code: 'martin', access: 'full' },
    { name: 'Lizzi', code: 'orangutan', access: 'full' },
    { name: 'Gemma', code: 'hornet', access: 'full' },
    { name: 'Ben', code: 'gorilla', access: 'full' },
    { name: 'Steve', code: 'spoonbill', access: 'full' },
    { name: 'Sue', code: 'lobster', access: 'full' },
    { name: 'Kelly', code: 'monkey', access: 'full' },
    { name: 'Lee', code: 'wallaroo', access: 'full' },
    { name: 'Mark', code: 'robin', access: 'full' },
    { name: 'Lindsay', code: 'kingfisher', access: 'full' },
    { name: 'Margaret Sherriff', code: 'yak', access: 'full' },
    { name: 'Margaret Shepard', code: 'platypus', access: 'full' },
    { name: 'Anne Wilson', code: 'treecreeper', access: 'full' },
    { name: 'John Wilson', code: 'camel', access: 'full' },
    { name: 'Julie', code: 'butterfly', access: 'full' },
    { name: 'Max', code: 'foal', access: 'full' },
    { name: 'Rich', code: 'badger', access: 'out-of-town' },
    { name: 'Laura', code: 'lovebird', access: 'out-of-town' },
    { name: 'Matt', code: 'llama', access: 'out-of-town' },
    { name: 'Giulia', code: 'shark', access: 'out-of-town' },
    { name: 'Ellie', code: 'jay', access: 'out-of-town' },
    { name: 'Miles', code: 'cow', access: 'out-of-town' },
    { name: 'Steph', code: 'hen', access: 'out-of-town' },
    { name: 'Ollie', code: 'redkite', access: 'out-of-town' },
    { name: 'Josh Brighton', code: 'turkey', access: 'out-of-town' },
    { name: 'Daisy', code: 'zebra', access: 'out-of-town' },
    { name: 'Dan', code: 'ant', access: 'out-of-town' },
    { name: 'Tom', code: 'baboon', access: 'out-of-town' },
    { name: 'Amy', code: 'starling', access: 'out-of-town' },
    { name: 'Ian', code: 'grasshopper', access: 'out-of-town' },
    { name: 'Tascha', code: 'stork', access: 'out-of-town' },
    { name: 'Connor', code: 'impala', access: 'out-of-town' },
    { name: 'Piero', code: 'axolotl', access: 'out-of-town' },
    { name: 'George', code: 'fieldfare', access: 'out-of-town' },
    { name: 'Matthew', code: 'stagbeetle', access: 'full' },
    { name: 'Dianna', code: 'cormorant', access: 'full' },
    { name: 'Joy', code: 'lynx', access: 'full' },
    { name: 'Nick', code: 'kitten', access: 'full' },
    { name: 'Isabelle', code: 'python', access: 'full' },
    { name: 'Joel', code: 'echidna', access: 'full' },
    { name: 'Livvie', code: 'cheetah', access: 'full' },
    { name: 'Hannah', code: 'glowworm', access: 'full' },
    { name: 'Phill', code: 'mink', access: 'full' },
    { name: 'Anne', code: 'whale', access: 'full' },
    { name: 'Gary', code: 'crocodile', access: 'full' },
    { name: 'Kate', code: 'hippo', access: 'full' },
    { name: 'Lukas', code: 'sandpiper', access: 'full' },
    { name: 'Emma', code: 'dolphin', access: 'full' },
    { name: 'Matt', code: 'tern', access: 'full' },
    { name: 'Pete', code: 'cat', access: 'full' },
    { name: 'Lois', code: 'elk', access: 'full' },
    { name: 'Ian Church', code: 'tiger', access: 'full' },
    { name: 'Jenny', code: 'spider', access: 'full' },
    { name: 'Ross', code: 'puffin', access: 'full' },
    { name: 'Ruth', code: 'ibis', access: 'full' },
    { name: 'Gabby', code: 'tapir', access: 'full' },
    { name: 'Terry', code: 'donkey', access: 'full' },
    { name: 'Jo', code: 'gecko', access: 'full' },
    { name: 'Magnus', code: 'crab', access: 'full' },
    { name: 'Rachel', code: 'quokka', access: 'full' },
    { name: 'Lawrence', code: 'sheep', access: 'full' },
    { name: 'Maisie', code: 'dachshund', access: 'full' },
    { name: 'Chris', code: 'spaniel', access: 'full' },
    { name: 'Jason', code: 'jackal', access: 'full' },
    { name: 'Catrina', code: 'caribou', access: 'full' },
    { name: 'Dean', code: 'bison', access: 'full' },
    { name: 'Avril', code: 'tortoise', access: 'full' },
    { name: 'Annie', code: 'swan', access: 'full' },
    { name: 'Simon', code: 'seahorse', access: 'full' },
    { name: 'Georgia', code: 'ladybird', access: 'full' },
    { name: 'Jonny', code: 'rhino', access: 'full' },
    { name: 'Lisa', code: 'canary', access: 'full' },
    { name: 'James', code: 'seal', access: 'full' },
    { name: 'Ross', code: 'plover', access: 'full' },
    { name: 'Laura', code: 'firecrest', access: 'full' },
    { name: 'Mark Drummer', code: 'gibbon', access: 'full' },
    { name: 'Janet', code: 'alligator', access: 'full' },
    { name: 'Lauren', code: 'tangerine', access: 'out-of-town' },
    { name: 'Eve', code: 'tangerine', access: 'out-of-town' },
    { name: 'Callum', code: 'tangerine', access: 'out-of-town' },
    { name: 'Karen', code: 'teal', access: 'full' },
    { name: 'Andy', code: 'puppy', access: 'full' },
    { name: 'Isaac', code: 'buffalo', access: 'full' },
    { name: 'Jess', code: 'sparrow', access: 'full' },
    { name: 'Andy', code: 'pangolin', access: 'full' },
    { name: 'Heather', code: 'collie', access: 'full' },
    { name: 'Jonathan', code: 'deer', access: 'full' },
    { name: 'Debra', code: 'whitethroat', access: 'full' },
    { name: 'Glen', code: 'chick', access: 'full' },
    { name: 'Aunty Pat', code: 'anteater', access: 'full' },
    { name: 'Mandy', code: 'ocelot', access: 'full' },
    { name: 'Mike', code: 'alpaca', access: 'full' },
    { name: 'Sean', code: 'squirrel', access: 'full' },
    { name: 'Natalie', code: 'parrot', access: 'full' },
    { name: 'Heather', code: 'damselfly', access: 'full' },
    { name: 'Heather\'s Husband', code: 'crane', access: 'full' },

    // Evening guests
    { name: 'Tim', code: 'warbler', access: 'evening' },
    { name: 'Hollie', code: 'capybara', access: 'evening' },
    { name: 'Emma', code: 'husky', access: 'evening' },
    { name: 'Lisa', code: 'crow', access: 'evening' },
    { name: 'Owen', code: 'goat', access: 'evening' },
    { name: 'Callum', code: 'ape', access: 'evening' },
    { name: 'Karen Rex', code: 'moorhen', access: 'evening' },
    { name: 'Andy Rex', code: 'egret', access: 'evening' },
    { name: 'Amy', code: 'blackbird', access: 'evening' },
    { name: 'Cat', code: 'skylark', access: 'evening' },
    { name: 'Jess', code: 'kestrel', access: 'evening' },
    { name: 'George', code: 'dog', access: 'evening' },
    { name: 'Trevor', code: 'rooster', access: 'evening' },
    { name: 'Mary', code: 'snail', access: 'evening' },
    { name: 'Will', code: 'bobcat', access: 'evening' },
    { name: 'Emma', code: 'hound', access: 'evening' },
    { name: 'Luke', code: 'finch', access: 'evening' },
    { name: 'Tegan', code: 'giraffe', access: 'evening' },
    { name: 'Lewis', code: 'dormouse', access: 'evening' },
    { name: 'Auntie Angela', code: 'raccoon', access: 'evening' },
    { name: 'Jed', code: 'squid', access: 'evening' },
    { name: 'Livvie', code: 'flamingo', access: 'evening' },
    { name: 'George', code: 'wolf', access: 'evening' },
    { name: 'Ali', code: 'lamb', access: 'evening' },
    { name: 'Andy Ferguson', code: 'viper', access: 'evening' },
    { name: 'Julie', code: 'bat', access: 'evening' },
    { name: 'Alan', code: 'swallow', access: 'evening' },
    { name: 'Mark\'s Wife', code: 'avocet', access: 'evening' },
    { name: 'Suade', code: 'nuthatch', access: 'evening' },
    { name: 'Charlotte', code: 'firefly', access: 'evening' },
    { name: 'Johnny', code: 'pony', access: 'evening' },
    { name: 'Amelia', code: 'bilby', access: 'evening' },
    { name: 'Tia', code: 'rook', access: 'evening' },
    { name: 'Laura (Neighbor)', code: 'macaw', access: 'evening' },
    { name: 'Katlyn', code: 'mare', access: 'evening' },
    { name: 'Ellie (St James)', code: 'fawn', access: 'evening' },
    { name: 'John (St James)', code: 'orca', access: 'evening' },
    { name: 'Tim (Keyzo)', code: 'mongoose', access: 'evening' },
    { name: 'Will (Keyzo)', code: 'bittern', access: 'evening' },
    { name: 'Tahla (Keyzo)', code: 'goose', access: 'evening' },
    { name: 'Therisa (Keyzo)', code: 'ray', access: 'evening' },
    { name: 'Iwona (Keyzo)', code: 'stoat', access: 'evening' },
    { name: 'Shane (Keyzo)', code: 'toad', access: 'evening' },
    { name: 'Sarah (Franklin)', code: 'shrimp', access: 'evening' },
    { name: 'Jez (Franklin)', code: 'kangaroo', access: 'evening' },
    { name: 'Jess Ryley', code: 'heron', access: 'evening' },
];
