/*
  Guest invite codes

  code   = first 3 letters of first name + 27
           e.g. Wendy -> Wen27, Zara -> Zar27
  access = "full" or "evening"
           (which view file they see after entering their code)

  If two people would get the same code, add a letter:
  And27, And27a, And27b, ...

  To add a guest, copy a line and fill in name / code / access.
*/

export const GUESTS = [
    { name: 'Mike (Groom)', code: 'Mik27', access: 'full' },
    { name: 'Jess (Bride)', code: 'Jes27', access: 'full' },

    { name: 'Debs', code: 'Deb27', access: 'full' },
    { name: 'Andy', code: 'And27', access: 'full' },
    { name: 'Andrea', code: 'And27a', access: 'full' },
    { name: 'Wendy', code: 'Wen27', access: 'full' },
    { name: 'Andy', code: 'And27b', access: 'full' },
    { name: 'Tom', code: 'Tom27', access: 'full' },
    { name: 'Abbie', code: 'Abb27', access: 'full' },
    { name: 'Jake', code: 'Jak27', access: 'full' },
    { name: 'Pei', code: 'Pei27', access: 'full' },
    { name: 'Lauren', code: 'Lau27', access: 'full' },
    { name: 'Lewis', code: 'Lew27', access: 'full' },
    { name: 'Eve', code: 'Eve27', access: 'full' },
    { name: 'Josh', code: 'Jos27', access: 'full' },
    { name: 'Niamh', code: 'Nia27', access: 'full' },
    { name: 'Chelsy', code: 'Che27', access: 'full' },
    { name: 'Jonny', code: 'Jon27', access: 'full' },
    { name: 'Tori', code: 'Tor27', access: 'full' },
    { name: 'Kay', code: 'Kay27', access: 'full' },
    { name: 'Katie Lou', code: 'Kat27', access: 'full' },
    { name: 'Lizzi', code: 'Liz27', access: 'full' },
    { name: 'Gemma', code: 'Gem27', access: 'full' },
    { name: 'Ben', code: 'Ben27', access: 'full' },
    { name: 'Steve', code: 'Ste27', access: 'full' },
    { name: 'Sue', code: 'Sue27', access: 'full' },
    { name: 'Kelly', code: 'Kel27', access: 'full' },
    { name: 'Lee', code: 'Lee27', access: 'full' },
    { name: 'Mark', code: 'Mar27', access: 'full' },
    { name: 'Lindsay', code: 'Lin27', access: 'full' },
    { name: 'Margaret Sherriff', code: 'Mar27a', access: 'full' },
    { name: 'Margaret Shepard', code: 'Mar27b', access: 'full' },
    { name: 'Anne Wilson', code: 'Ann27', access: 'full' },
    { name: 'John Wilson', code: 'Joh27', access: 'full' },
    { name: 'Julie', code: 'Jul27', access: 'full' },
    { name: 'Max', code: 'Max27', access: 'full' },
    { name: 'Rich', code: 'Ric27', access: 'full' },
    { name: 'Laura', code: 'Lau27a', access: 'full' },
    { name: 'Matt', code: 'Mat27', access: 'full' },
    { name: 'Giulia', code: 'Giu27', access: 'full' },
    { name: 'Elle', code: 'Ell27', access: 'full' },
    { name: 'Miles', code: 'Mil27', access: 'full' },
    { name: 'Steph', code: 'Ste27a', access: 'full' },
    { name: 'Ollie', code: 'Oll27', access: 'full' },
    { name: 'Josh', code: 'Jos27a', access: 'full' },
    { name: 'Daisy', code: 'Dai27', access: 'full' },
    { name: 'Dan', code: 'Dan27', access: 'full' },
    { name: 'Tom', code: 'Tom27a', access: 'full' },
    { name: 'Amy', code: 'Amy27', access: 'full' },
    { name: 'Ian', code: 'Ian27', access: 'full' },
    { name: 'Tascha', code: 'Tas27', access: 'full' },
    { name: 'Connor', code: 'Con27', access: 'full' },
    { name: 'Piero', code: 'Pie27', access: 'full' },
    { name: 'George', code: 'Geo27', access: 'full' },
    { name: 'Matthew', code: 'Mat27a', access: 'full' },
    { name: 'Dianna', code: 'Dia27', access: 'full' },
    { name: 'Joy', code: 'Joy27', access: 'full' },
    { name: 'Nick', code: 'Nic27', access: 'full' },
    { name: 'Isabelle', code: 'Isa27', access: 'full' },
    { name: 'Joel', code: 'Joe27', access: 'full' },
    { name: 'Noah', code: 'Noa27', access: 'full' },
    { name: 'Hannah', code: 'Han27', access: 'full' },
    { name: 'Phill', code: 'Phi27', access: 'full' },
    { name: 'Anne', code: 'Ann27a', access: 'full' },
    { name: 'Gary', code: 'Gar27', access: 'full' },
    { name: 'Kate', code: 'Kat27a', access: 'full' },
    { name: 'Lukas', code: 'Luk27', access: 'full' },
    { name: 'Emma', code: 'Emm27', access: 'full' },
    { name: 'Matt', code: 'Mat27b', access: 'full' },
    { name: 'Pete', code: 'Pet27', access: 'full' },
    { name: 'Lois', code: 'Loi27', access: 'full' },
    { name: 'Ian Church', code: 'Ian27a', access: 'full' },
    { name: 'Jenny', code: 'Jen27', access: 'full' },
    { name: 'Ross', code: 'Ros27', access: 'full' },
    { name: 'Ruth', code: 'Rut27', access: 'full' },
    { name: 'Gabby', code: 'Gab27', access: 'full' },
    { name: 'Terry', code: 'Ter27', access: 'full' },
    { name: 'Jo', code: 'Jo27', access: 'full' },
    { name: 'Magnus', code: 'Mag27', access: 'full' },
    { name: 'Rachel', code: 'Rac27', access: 'full' },
    { name: 'Lawrence', code: 'Law27', access: 'full' },
    { name: 'Maisie', code: 'Mai27', access: 'full' },
    { name: 'Chris', code: 'Chr27', access: 'full' },
    { name: 'Jason', code: 'Jas27', access: 'full' },
    { name: 'Catrina', code: 'Cat27', access: 'full' },
    { name: 'Dean', code: 'Dea27', access: 'full' },
    { name: 'Avril', code: 'Avr27', access: 'full' },
    { name: 'Annie', code: 'Ann27b', access: 'full' },
    { name: 'Simon', code: 'Sim27', access: 'full' },
    { name: 'Georgia', code: 'Geo27a', access: 'full' },
    { name: 'Jonny', code: 'Jon27a', access: 'full' },
    { name: 'Lisa', code: 'Lis27', access: 'full' },
    { name: 'James', code: 'Jam27', access: 'full' },
    { name: 'Ross', code: 'Ros27a', access: 'full' },
    { name: 'Laura', code: 'Lau27b', access: 'full' },
    { name: 'Mark Drummer', code: 'Mar27c', access: 'full' },
    { name: 'Janet', code: 'Jan27', access: 'full' },
    { name: 'Lauren', code: 'Lau27c', access: 'full' },
    { name: 'Eve', code: 'Eve27a', access: 'full' },
    { name: 'Callum', code: 'Cal27', access: 'full' },
    { name: 'Karen', code: 'Kar27', access: 'full' },
    { name: 'Andy', code: 'And27c', access: 'full' },
    { name: 'Isaac', code: 'Isa27a', access: 'full' },
    { name: 'Jess', code: 'Jes27a', access: 'full' },
    { name: 'Andy', code: 'And27d', access: 'full' },
    { name: 'Heather', code: 'Hea27', access: 'full' },
    { name: 'Jonathan', code: 'Jon27b', access: 'full' },
    { name: 'Debra', code: 'Deb27a', access: 'full' },
    { name: 'Glen', code: 'Gle27', access: 'full' },
    { name: 'Aunty Pat', code: 'Aun27', access: 'full' },
    { name: 'Mandy', code: 'Man27', access: 'full' },
    { name: 'Mike', code: 'Mik27a', access: 'full' },
    { name: 'Sean', code: 'Sea27', access: 'full' },
    { name: 'Natalie', code: 'Nat27', access: 'full' },
    { name: 'Heather', code: 'Hea27a', access: 'full' },
    { name: "Heather's Husband", code: 'Hea27b', access: 'full' }
];
